version: "3.3"
services:
    feedurl:
        container_name: feedurl
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: feedurl:$FEEDURL_VERSION
        restart: always
        expose:
            - "80"
            - "443"
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST:?set it in .env}
            - APACHE_RUN_USER=www-data
            - APACHE_RUN_GROUP=www-data
            - LETSENCRYPT_HOST=${VIRTUAL_HOST:?set it in .env}
            - LETSENCRYPT_EMAIL=frederick@tyteca.net
        volumes:
            - .:/app
            - /etc/localtime:/etc/localtime:ro
        healthcheck:
            test: bash -c "[ -f /app/vendor/autoload.php ]"
            timeout: 10s
            retries: 30
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        external: true
